import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { helvetica, neutra } from "@/fonts/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${helvetica.variable} ${neutra.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col max-w-7xl lg:max-w-full  mx-auto">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
